services:
  web:
    image: node:24.2.0-alpine3.22
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
#      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
